# Generated by Django 2.2.5 on 2019-10-06 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('precio_sugerido', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='El precio debe ser mayor a $0')], verbose_name='Precio sugerido de Venta')),
            ],
        ),
    ]
